# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: ip-seg6-encap

builds:
  - id: ip-seg6-encap
    main: .
    binary: ip-seg6-encap
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: ip-seg6-encap
    ids:
      - ip-seg6-encap
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256
